-d C:\Users\BEK\Desktop\CustomRISCVComputerOnFpga2\CustomRISCVComputerOnFpga2\reis\kim_jong_un\impl\gwsynthesis\32bit_Computer.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\BEK\Desktop\CustomRISCVComputerOnFpga2\CustomRISCVComputerOnFpga2\reis\kim_jong_un\src\32bitv2.cst
-cfg C:\Users\BEK\Desktop\CustomRISCVComputerOnFpga2\CustomRISCVComputerOnFpga2\reis\kim_jong_un\impl\pnr\device.cfg
-sdc C:\Users\BEK\Desktop\CustomRISCVComputerOnFpga2\CustomRISCVComputerOnFpga2\reis\kim_jong_un\src\32bit.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 2
-clock_route_order 1
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
