/*
 * w_file_stdc.c — bare-metal FPGA replacement
 *
 * WAD address comes from linker symbol _wad_start — no hardcoded address,
 * no fopen/fread. Packed immediately after .text in the binary.
 */

#include <stddef.h>
#include <string.h>
#include "w_file.h"
#include "z_zone.h"

/* Linker symbols generated by objcopy */
extern const unsigned char _binary_doom1_wad_start[];
extern const unsigned char _binary_doom1_wad_end[];

#define WAD_BASE  (_binary_doom1_wad_start)
#define WAD_SIZE  ((unsigned int)(_binary_doom1_wad_end - _binary_doom1_wad_start))

typedef struct {
    wad_file_t wad;
} stdc_wad_file_t;

extern wad_file_class_t stdc_wad_file;

static wad_file_t *W_StdC_OpenFile(char *path)
{
    stdc_wad_file_t *result;

    if (!strstr(path, "doom1"))
        return NULL;

    result = Z_Malloc(sizeof(stdc_wad_file_t), PU_STATIC, 0);
    result->wad.file_class = &stdc_wad_file;
    result->wad.mapped     = NULL;
    result->wad.length     = WAD_SIZE;
    return &result->wad;
}
static void W_StdC_CloseFile(wad_file_t *wad)
{
    Z_Free(wad);
}

static size_t W_StdC_Read(wad_file_t *wad, unsigned int offset,
                           void *buffer, size_t buffer_len)
{
    (void)wad;
    if (offset >= WAD_SIZE) return 0;
    if (offset + buffer_len > (size_t)WAD_SIZE)
        buffer_len = WAD_SIZE - offset;
    memcpy(buffer, WAD_BASE + offset, buffer_len);
    return buffer_len;
}

wad_file_class_t stdc_wad_file =
{
    W_StdC_OpenFile,
    W_StdC_CloseFile,
    W_StdC_Read,
};
